server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb+srv://mongodb:root@cluster-0.ccexft8.mongodb.net/microservice?retryWrites=true&w=majority

  application:
    name: RATING-SERVICE

  config:
    import: optional:configserver:http://localhost:8085

# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka